export const keys = {
  brands: {
    fetchAllBrands: 'fetchAllBrands',
    fetchAllBrandsPagination: 'fetchAllBrandsPagination',
    fetchAvailableBrands: 'fetchAvailableBrands',
    fetchAvailableBrandsPagination: 'fetchAvailableBrandsPagination',
    createBrand: 'createBrand',
    updateBrand: 'updateBrand',
    deleteBrand: 'deleteBrand',
  },
  categories: {
    fetchAllCategories: 'fetchAllCategories',
    fetchAllCategoriesPagination: 'fetchAllCategoriesPagination',
    fetchAvailableCategories: 'fetchAvailableCategories',
    fetchAvailableCategoriesPagination: 'fetchAvailableCategoriesPagination',
    createCategory: 'createCategory',
    updateCategory: 'updateCategory',
    deleteCategory: 'deleteBrand',
  },
  appConfigs: {
    fetchAllAppConfigs: 'fetchAllAppConfigs',
    fetchAllAppConfigsPagination: 'fetchAllAppConfigsPagination',
    fetchAvailableAppConfigs: 'fetchAvailableAppConfigs',
    fetchAvailableAppConfigsPagination: 'fetchAvailableAppConfigsPagination',
    createAppConfig: 'createAppConfig',
    updateAppConfig: 'updateAppConfig',
    deleteAppConfig: 'deleteAppConfig',
  },
  tags: {
    fetchAllTags: 'fetchAllTags',
    fetchAllTagsPagination: 'fetchAllTagsPagination',
    fetchAvailableTags: 'fetchAvailableTags',
    fetchAvailableTagsPagination: 'fetchAvailableTagsPagination',
    createTag: 'createTag',
    updateTag: 'updateTag',
    deleteTag: 'deleteTag',
  },
  contacts: {
    fetchAllContacts: 'fetchAllContacts',
    fetchAllContactsPagination: 'fetchAllContactsPagination',
    fetchAvailableContacts: 'fetchAvailableContacts',
    fetchAvailableContactsPagination: 'fetchAvailableContactsPagination',
    createContact: 'createContact',
    updateContact: 'updateContact',
    deleteContact: 'deleteContact',
  },
  products: {
    fetchAllProducts: 'fetchAllProducts',
    fetchAllProductsPagination: 'fetchAllProductsPagination',
    fetchAvailableProducts: 'fetchAvailableProducts',
    fetchAvailableProductsPagination: 'fetchAvailableProductsPagination',
    createProduct: 'createProduct',
    updateProduct: 'updateProduct',
    updateProductImages: 'updateProductImages',
    deleteProduct: 'deleteProduct',
  },
};

export const DEFAULT_STATE_TIME = 60000;
